/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as PlayRoomIdRouteImport } from './routes/play.$roomId'

const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoomIdRoute = PlayRoomIdRouteImport.update({
  id: '/play/$roomId',
  path: '/play/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/lobby'
    | '/play/$roomId'
    | '/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/lobby'
    | '/play/$roomId'
    | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/lobby'
    | '/play/$roomId'
    | '/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LobbyRoute: typeof LobbyRoute
  PlayRoomIdRoute: typeof PlayRoomIdRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$roomId': {
      id: '/play/$roomId'
      path: '/play/$roomId'
      fullPath: '/play/$roomId'
      preLoaderRoute: typeof PlayRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  LobbyRoute: LobbyRoute,
  PlayRoomIdRoute: PlayRoomIdRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
